import { Box, ListItem, ListItemText, Typography } from '@mui/material'
import { PageTitle } from '../../components/PageTitle'
import { ImageComponent } from '../../components/ImageComponent'
import { Section } from '../../components/Section'
import CodeEditorField from '../../components/CodeEditorField'
import { NavLink } from 'react-router-dom'
import { ProChip } from '../../components/ProChip'
import { BetaDisclaimer } from '../../components/BetaDisclaimer'
import DownloadMergeReports from '../../components/DownloadMergeReports'
import { SolidWorksTag, SwoodDataDirectoryTag, SwoodDesignTag, SwoodNestingTag } from '../../components/NameTags'
import MergeReportDiagram from '../../Flow Diagrams/MergeReportDiagram'

const MergeReports = () => {
	return (
		<>
			<PageTitle title="How to merge nest and design reports" pro={true} beta={true} />
			<nav>
				<ul>
					<li>
						<a href="#Overview">Overview</a>
					</li>
					<li>
						<a href="#Terminology">Terminology</a>
					</li>
					<li>
						<a href="#Workflow">Workflow</a>
					</li>
					<li>
						<a href="#FAQs">FAQs</a>
					</li>
					<li>
						<a href="#Requirements">Requirements</a>
					</li>
					<li>
						<a href="#Disclaimer">MergeReports disclaimer</a>
					</li>
					<li>
						<a href="#Setup">How to set up the MergeReports application</a>
					</li>
				</ul>
			</nav>
			<Section id="Overview" title="Overview">
				<Typography>
					When using <SwoodDesignTag /> and <SwoodNestingTag />, users must manage multiple assemblies: one or more design assemblies and the nesting assembly. This separation often leads to issues with reports due to the division of data. For example, nesting projects may not include all project components (such as hardware) or information about the frames used. Conversely, design projects lack details about the nested sheets.
				</Typography>
				<Typography>
					To address this, a new <span className="highlight">MergeReports</span> application has been developed to consolidate the data from Design and Nesting projects into a single report. Please read further to understand its workflow, FAQs, and setup.
				</Typography>
				<Typography>It is important to note that this application is currently in the beta stage. As such, it may contain errors and bugs. We appreciate your understanding and encourage you to report any issues you encounter to help us improve the application.</Typography>
			</Section>

			<Section id="Terminology" title="Terminology">
				<Typography>Below is a list of the terminology used throughout this article:</Typography>
				<ListItem>
					<ListItemText
						primary="Design Project"
						secondary={
							<>
								A project or file created using <SwoodDesignTag />, such as a panel, frame, or layout assembly.
							</>
						}
					/>
				</ListItem>
				<ListItem>
					<ListItemText
						primary="Design Report"
						secondary={
							<>
								A report generated from a <SwoodDesignTag /> project.
							</>
						}
					/>
				</ListItem>
				<ListItem>
					<ListItemText
						primary="Nesting Project"
						secondary={
							<>
								A project or file created using <SwoodNestingTag />.
							</>
						}
					/>
				</ListItem>
				<ListItem>
					<ListItemText
						primary="Nesting Report"
						secondary={
							<>
								A report generated from a <SwoodNestingTag /> project.
							</>
						}
					/>
				</ListItem>
				<ListItem>
					<ListItemText
						primary="Merged Report"
						secondary={
							<>
								A report generated by the <span className="highlight">MergeReports</span> application
							</>
						}
					/>
				</ListItem>
				<ListItem>
					<ListItemText
						primary="Nesting Source Files"
						secondary={
							<>
								Projects or files added as Source Files to the <SwoodNestingTag /> project.
							</>
						}
					/>
				</ListItem>
				<ImageComponent source="./images/MergeReportsSourceFilesNest.png" size="600px" />
			</Section>

			<Section id="Workflow" title="Workflow">
				<Typography>To merge a nest report with the reports of its source files, follow the steps outlined below:</Typography>

				<ol>
					<li>Create Design Projects.</li>
					<li>Generate Design Reports.</li>
					<li>Create a Nesting Project using the Design Projects as Nesting Source Files.</li>
					<li>Generate the Nesting Report.</li>
					<li>
						The <span className="highlight">MergeReports</span> application will automatically generate a merged report.
					</li>
				</ol>
				<MergeReportDiagram />
			</Section>
			<Section id="FAQs" title="FAQs">
				<ListItem>
					<ListItemText primary="Can I use a single source file for the Nesting project?" secondary="Yes, you can use any number of source files in the nesting project." />
				</ListItem>

				<ListItem>
					<ListItemText
						primary="How can I access the merged report?"
						secondary={
							<>
								After the nest report is completed, you can access the merged report in the Encoding Report Screen by clicking <span className="param">Documents &gt; Home Merged Report</span>. Note that you can also access the merged report through Windows Explorer.
							</>
						}
					/>
				</ListItem>
				<ImageComponent source="./images/MergeReportsOpen.png" size="300px" />
				<ListItem>
					<ListItemText primary="Where is the merged report saved?" secondary="The merged report is saved in the same directory as the nested report. This cannot be changed." />
				</ListItem>
				<ListItem>
					<ListItemText
						primary="What will be the name of the merged report?"
						secondary={
							<>
								The merged report will be automatically named <span className="highlight">Merged - &lt;Nest Report Name&gt;</span>. This cannot be changed.
							</>
						}
					/>
				</ListItem>

				<ListItem>
					<ListItemText primary="What should I do if any of the models change?" secondary="If a model changes, generate all associated Design reports followed by the Nesting report. This will automatically regenerate the merged report with the updated data." />
				</ListItem>

				<ListItem>
					<ListItemText primary="Can I merge with older report versions?" secondary="No, all reports must be version 2.10.3 or newer." />
				</ListItem>
				<ListItem>
					<ListItemText primary="Can I merge multiple Design projects without a Nest project?" secondary="This is not supported at the moment." />
				</ListItem>

				<ListItem>
					<ListItemText primary="Can I merge multiple Nest projects?" secondary="This is not supported at the moment." />
				</ListItem>
				<ListItem>
					<ListItemText primary="Are cutting patterns re-optimised in the merged report?" secondary="The merged report does not re-optimise cutting patterns from the Design projects. The original cutting patterns are retained, which may not be the most efficient solution." />
				</ListItem>
				<ListItem>
					<ListItemText primary="Can I use the Project Quantity Custom Property?" secondary={<>This is not supported at the moment.</>} />
				</ListItem>

				<ListItem>
					<ListItemText primary="Can I use the Quantity option in the nest project settings?" secondary="Yes. Keep in mind that in the merged report, the panel quantities from the nest project will take precedence." />
				</ListItem>
				<ImageComponent source="./images/MergeReportsNestQuantity.png" size="600px" />

				<ListItem>
					<ListItemText
						primary="What happens if not all of the source files have a design report?"
						secondary={
							<>
								The <span className="highlight">MergeReport</span> application will only merge the available data from existing reports. As a result, some information such as hardware, frames, and unnested panels may be missing in the merged report.
							</>
						}
					/>
				</ListItem>

				<ListItem>
					<ListItemText
						primary="What happens if none of the source files have a design report?"
						secondary={
							<>
								The <span className="highlight">MergeReport</span> application will not generate any files. You will also notice the message below when clicking on <span className="param">Documents &gt; Home Merged Report</span>.
							</>
						}
					/>
				</ListItem>
				<ImageComponent source="./images/MergeReportsError.png" size="600px" />

				<ListItem>
					<ListItemText primary="Will the merged report folder be deleted when the nest report is run again?" secondary="Yes, all files in the existing merged report folder will be deleted before the merge process begins. This behavior is consistent whether you run a design or nest report. However, you will not be prompted to choose a different folder." />
				</ListItem>

				<ListItem>
					<ListItemText primary="How can I identify what reports have been merged?" secondary="At present, there is no interface to display this information. However, you can use the Raw Data Viewer to view the merged data." />
				</ListItem>
				<ImageComponent source="./images/MergeReportsData.gif" size="800px" />

				<ListItem>
					<ListItemText primary="What image will the merged report display on the home page?" secondary="The report will display the image from one of the nest source files. It is not possible to specify which source file's image will be used." />
				</ListItem>

				<ListItem>
					<ListItemText primary="Should I disable the 'Insert Not Nested Parts' option in the nest settings?" secondary="Yes. Enabling this option will insert a single instance of un-nested parts, which can result in incorrect quantity values." />
				</ListItem>
				<ImageComponent source="./images/MergeReportsNotNestedOption.png" size="600px" />

				<ListItem>
					<ListItemText primary="Why are there original copies of the nest and design reports in the merged report folder?" secondary="These files are remnants of the merge process and are no longer needed once the merge is complete. Future developments may enable referencing these reports." />
				</ListItem>

				<ListItem>
					<ListItemText
						primary="How can I provide feedback, suggestions, or report bugs?"
						secondary={
							<>
								We value your input and encourage you to share any feedback, suggestions, or bugs you encounter. Please contact us at <a href="mailto:SwoodApps@solidsolutions.co.uk">SwoodApps@solidsolutions.co.uk</a>. Your contributions help us improve and enhance our software.
							</>
						}
					/>
				</ListItem>
			</Section>

			<Section id="Requirements" title="Requirements">
				<ol>
					<li>
						SwoodReport Pro
						<ProChip /> version 2.10.3 or newer
					</li>
					<li>Swood 2024 SP0.0 or newer</li>
				</ol>
			</Section>

			<Box className="red">
				<Section id="Disclaimer" title="MergeReports disclaimer">
					<BetaDisclaimer />
				</Section>
			</Box>

			<Section id="Setup" title="How to set up the MergeReports application">
				<ol>
					<li>
						Download <span className="highlight">MergeReports.exe</span>.
					</li>

					<Typography className="red">Please note that your eligibility for this version depends on your Subscription Renewal Date.</Typography>

					<DownloadMergeReports />
					<li>
						Ensure that <span className="highlight">MergeReports.exe</span> has not been blocked by your machine. Right-click on the <span className="highlight">MergeReports.exe</span> application, then go to <span className="param">Properties &gt; Unblock &gt; OK</span>. If the <span className="param">Unblock</span> option is not present, it means the file has not been blocked, and you can skip this step.
					</li>
					<ImageComponent source="./images/MergeReportsUnblock.png" size="300px" />
					<li>
						Place <span className="highlight">MergeReports.exe</span> in the <span className="param">&lt;SWOOD DATA DIRECTORY&gt;\DAT\Documents\Report Posts</span> folder. Click <NavLink to="/SwoodDataDirectory">here</NavLink> to learn how to find the <SwoodDataDirectoryTag />.
					</li>
					<li>
						Open the following file with any text editor (e.g., Notepad): <span className="param">&lt;SWOOD DATA DIRECTORY&gt;\DAT\Report.cfg</span>.
					</li>
					<li>
						Scroll down to the <span className="param">(DOCUMENTS) &gt; ADDITIONAL DOCUMENTS</span> section and copy and paste the code below:
					</li>
					<CodeEditorField
						text={`
    [MERGE_REPORT]
		PROCESSON = REPORT
		TYPEDOCUMENT = TEMPLATE
		PATH = <REPORTPATH>\\Documents\\Sheets_<AssemblyName>.txt
		CONDITION = REPORT_ISNESTINGPROJECT
		AUTOPROCESS = 1
		HIDDEN = 1
		POSTPROCESS_WAITFOREXIT = 1
		PRIORITY = 1
		POSTPROCESS = DAT\\Documents\\Report Posts\\MergeReports.exe
		POSTPROCESSARGS = --DatabasePath "<REPORTPATH>\\Documents\\Database_<AssemblyName>.js"
		FORCED_STORAGE_TYPE = 1
		[[TEMPLATE
			MODE = REPLACE
			VARSEPARATORIN = "«"
			VARSEPARATOROUT = "»"
			TEMPLATESRC = <APP.USERPATH>\\DAT\\Documents\\WEB\\Sheets.html
		]]

	[Home Merged Report]
		PROCESSON = REPORT
		PATH = <REPORTPATH>\\..\\Merged - <AssemblyName>\\Home_Merged - <AssemblyName>.html
		CONDITION = REPORT_ISNESTINGPROJECT
		AUTOPROCESS = 1
		HIDDEN = 0
`}
					/>
					<Typography>The end result should look something like this:</Typography>
					<ImageComponent source="./images/MergeReportsCFG.png" size="600px" />
					<li>
						Save the <span className="highlight">Report.cfg</span> file and restart <SolidWorksTag />.
					</li>
					<li>
						Follow the steps outlined in <a href="#Workflow">Workflow</a> to create your first merged report.
					</li>
				</ol>
			</Section>
		</>
	)
}

export default MergeReports
