import { Box, ListItem, ListItemText, Typography } from '@mui/material'
import { PageTitle } from '../../components/PageTitle'
import { ImageComponent } from '../../components/ImageComponent'
import { Section } from '../../components/Section'
import { NavLink } from 'react-router-dom'
import { ProChip } from '../../components/ProChip'
import { BetaDisclaimer } from '../../components/BetaDisclaimer'
import DownloadSwoodMergePost from '../../components/DownloadSwoodMergePost'
import { SolidWorksTag, SwoodDataDirectoryTag, SwoodDesignTag, SwoodMergeTag, SwoodNestingTag } from '../../components/NameTags'
import SwoodMergeDiagram from '../../Flow Diagrams/SwoodMergeDiagram'

const SwoodMerge = () => {
	return (
		<>
			<PageTitle title="SwoodMerge" pro={true} beta={true} />
			<nav>
				<ul>
					<li>
						<a href="#Overview">Overview</a>
					</li>
					<li>
						<a href="#Terminology">Terminology</a>
					</li>
					<li>
						<a href="#Workflow">Workflow</a>
					</li>
					<li>
						<a href="#FAQs">FAQs</a>
					</li>
					<li>
						<a href="#Requirements">Requirements</a>
					</li>
					<li>
						<a href="#Disclaimer">SwoodMerge disclaimer</a>
					</li>
					<li>
						<a href="#Setup">How to set up SwoodMerge</a>
					</li>
				</ul>
			</nav>
			<Section id="Overview" title="Overview">
				<Typography>
					When using <SwoodDesignTag /> and <SwoodNestingTag />, users must manage multiple assemblies: one or more design assemblies and the nesting assembly. This separation often leads to issues with reports due to the division of data. For example, nesting projects may not include all project components (such as hardware) or information about the frames used. Conversely, design projects lack details about the nested sheets.
				</Typography>
				<Typography>
					To address this, a new <SwoodMergeTag /> has been developed to consolidate the data from Design and Nesting projects into a single report. Please read further to understand its workflow, FAQs, and setup.
				</Typography>
				<Typography>It is important to note that this application is currently in the beta stage. As such, it may contain errors and bugs. We appreciate your understanding and encourage you to report any issues you encounter to help us improve the application.</Typography>
			</Section>

			<Section id="Terminology" title="Terminology">
				<Typography>Below is a list of the terminology used throughout this article:</Typography>
				<ListItem>
					<ListItemText
						primary="Design Project"
						secondary={
							<>
								A project or file created using <SwoodDesignTag />, such as a panel, frame, or layout assembly.
							</>
						}
					/>
				</ListItem>
				<ListItem>
					<ListItemText
						primary="Design Report"
						secondary={
							<>
								A report generated from a <SwoodDesignTag /> project.
							</>
						}
					/>
				</ListItem>
				<ListItem>
					<ListItemText
						primary="Nesting Project"
						secondary={
							<>
								A project or file created using <SwoodNestingTag />.
							</>
						}
					/>
				</ListItem>
				<ListItem>
					<ListItemText
						primary="Nesting Report"
						secondary={
							<>
								A report generated from a <SwoodNestingTag /> project.
							</>
						}
					/>
				</ListItem>
				<ListItem>
					<ListItemText
						primary="Merged Report"
						secondary={
							<>
								A report generated by <SwoodMergeTag />
							</>
						}
					/>
				</ListItem>
				<ListItem>
					<ListItemText
						primary="Nesting Source Files"
						secondary={
							<>
								Projects or files added as Source Files to the <SwoodNestingTag /> project.
							</>
						}
					/>
				</ListItem>
				<ImageComponent source="./images/MergeReportsSourceFilesNest.png" size="600px" />
			</Section>

			<Section id="Workflow" title="Workflow">
				<Typography>To merge multiple reports, follow the steps outlined below:</Typography>

				<ol>
					<li>Create the different projects (Design, Cam, or Nesting).</li>
					<li>Generate the according reports.</li>
					<li>
						Select all projects in the <SwoodMergeTag /> app and merge them.
					</li>
				</ol>
				<SwoodMergeDiagram />
			</Section>
			<Section id="FAQs" title="FAQs">
				<ListItem>
					<ListItemText primary="Can I merge as many reports as I want?" secondary="Yes, you can use any number of reports." />
				</ListItem>

				<ListItem>
					<ListItemText primary="What should I do if any of the models change?" secondary="If a model changes, generate all associated reports and merge them again." />
				</ListItem>

				<ListItem>
					<ListItemText primary="Can I merge with older report versions?" secondary="No, all reports must be version 2.11.0 or newer." />
				</ListItem>
				<ListItem>
					<ListItemText primary="Are nesting sheets recalculated in the merged report?" secondary="The merged report does not re-optimise nested sheets. The original nested sheets are retained, which may not be the most efficient solution." />
				</ListItem>
				<ListItem>
					<ListItemText primary="Are cutting patterns re-optimised in the merged report?" secondary="The merged report does not re-optimise cutting patterns. The original cutting patterns are retained, which may not be the most efficient solution." />
				</ListItem>
				<ListItem>
					<ListItemText primary="Can I use the Project Quantity Custom Property?" secondary={<>This is not supported at the moment.</>} />
				</ListItem>
				<ListItem>
					<ListItemText primary="Is there a way to change the Projects Quantities of individual reports?" secondary={<>This is not supported at the moment.</>} />
				</ListItem>
				<ListItem>
					<ListItemText primary="How can I identify what reports have been merged?" secondary="At present, there is no interface to display this information. However, you can use the Raw Data Viewer to view the merged data." />
				</ListItem>
				<ImageComponent source="./images/MergeReportsData.gif" size="800px" />

				<ListItem>
					<ListItemText primary="What image will the merged report display on the home page?" secondary="The report will display the image from one of the nest source files. It is not possible to specify which source file's image will be used." />
				</ListItem>

				<ListItem>
					<ListItemText primary="Should I disable the 'Insert Not Nested Parts' option in the nest settings?" secondary="Yes. Enabling this option will insert a single instance of un-nested parts, which can result in incorrect quantity values." />
				</ListItem>
				<ImageComponent source="./images/MergeReportsNotNestedOption.png" size="600px" />

				<ListItem>
					<ListItemText primary="Why are there original copies of the nest and design reports in the merged report folder?" secondary="These files are remnants of the merge process and are no longer needed once the merge is complete. Future developments may enable referencing these reports." />
				</ListItem>

				<ListItem>
					<ListItemText
						primary="How can I provide feedback, suggestions, or report bugs?"
						secondary={
							<>
								We value your input and encourage you to share any feedback, suggestions, or bugs you encounter. Please contact us at <a href="mailto:SwoodApps@solidsolutions.co.uk">SwoodApps@solidsolutions.co.uk</a>. Your contributions help us improve and enhance our software.
							</>
						}
					/>
				</ListItem>
			</Section>

			<Section id="Requirements" title="Requirements">
				<ol>
					<li>
						SwoodReport Pro
						<ProChip /> version 2.11.0 or newer
					</li>
					<li>Swood 2024 SP0.0 or newer</li>
				</ol>
			</Section>

			<Box className="red">
				<Section id="Disclaimer" title="SwoodMerge disclaimer">
					<BetaDisclaimer />
				</Section>
			</Box>

			<Section id="Setup" title="How to set up SwoodMerge">
				<ol>
					<li>
						Download <span className="highlight">MergeReportPost.exe</span>.
					</li>

					<Typography className="red">Please note that your eligibility for this version depends on your Subscription Renewal Date.</Typography>

					<DownloadSwoodMergePost />
					<li>
						Ensure that <span className="highlight">MergeReportPost.exe</span> has not been blocked by your machine. Right-click on the <span className="highlight">MergeReportPost.exe</span> file, then go to <span className="param">Properties &gt; Unblock &gt; OK</span>. If the <span className="param">Unblock</span> option is not present, it means the file has not been blocked, and you can skip this step.
					</li>
					<ImageComponent source="./images/MergeReportsUnblock.png" size="300px" />
					<li>
						Place <span className="highlight">MergeReportPost.exe</span> in the <span className="param">&lt;SWOOD DATA DIRECTORY&gt;\DAT\Documents\Report Posts</span> folder. Click <NavLink to="/SwoodDataDirectory">here</NavLink> to learn how to find the <SwoodDataDirectoryTag />.
					</li>
					<li>
						Open the following file with any text editor (e.g., Notepad): <span className="param">&lt;SWOOD DATA DIRECTORY&gt;\DAT\Report.cfg</span>.
					</li>
					<li>
						Scroll down to the <span className="param">(DOCUMENTS) &gt; ADDITIONAL DOCUMENTS</span> section and copy and paste the code below:
					</li>

					<Typography>The end result should look something like this:</Typography>
					<ImageComponent source="./images/MergeReportsCFG.png" size="600px" />
					<li>
						Save the <span className="highlight">Report.cfg</span> file and restart <SolidWorksTag />.
					</li>
					<li>
						Follow the steps outlined in <a href="#Workflow">Workflow</a> to create your first merged report.
					</li>
				</ol>
			</Section>
		</>
	)
}

export default SwoodMerge
